#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
##
## Set Wallpaper in Hyprland

WALLPAPER='/home/rok/Pictures/wallpapers/wallpaper_2.jpg'

swaybg --output '*' --mode fill --image "$WALLPAPER"
